import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:equatable/equatable.dart';
import 'package:wms/features/supervisor/data/models/ai_override_model.dart';
import 'package:wms/features/supervisor/data/repositories/ai_review_repository.dart';
import 'package:supabase_flutter/supabase_flutter.dart';

abstract class AiReviewState extends Equatable {
  const AiReviewState();
  @override
  List<Object?> get props => [];
}

class AiReviewInitial extends AiReviewState {}
class AiReviewLoading extends AiReviewState {}
class AiReviewLoaded extends AiReviewState {
  final List<Map<String, dynamic>> pendingOrders;
  final List<AiOverrideModel> overrides;

  const AiReviewLoaded({required this.pendingOrders, this.overrides = const []});

  @override
  List<Object?> get props => [pendingOrders, overrides];
}
class AiReviewError extends AiReviewState {
  final String message;
  const AiReviewError(this.message);
  @override
  List<Object?> get props => [message];
}

class AiReviewCubit extends Cubit<AiReviewState> {
  final AiReviewRepository _repository;

  AiReviewCubit(this._repository) : super(AiReviewInitial());

  void loadPendingReviews() async {
    emit(AiReviewLoading());
    try {
      final orders = await _repository.getPendingAiOrders();
      emit(AiReviewLoaded(pendingOrders: orders));
    } catch (e) {
      emit(AiReviewError(e.toString()));
    }
  }

  Future<void> approveOrder(String orderId, AiOrderType type) async {
    try {
      await _repository.approveOrder(orderId, type);
      loadPendingReviews(); // Refresh
    } catch (e) {
      emit(AiReviewError(e.toString()));
    }
  }

  Future<void> overrideOrder({
    required String orderId,
    required AiOrderType orderType,
    required String justification,
    required Map<String, dynamic> aiSuggestion,
    required Map<String, dynamic> finalDecision,
  }) async {
    try {
      final override = AiOverrideModel(
        id: '', // Generated by DB
        orderType: orderType,
        orderId: orderId,
        overriddenBy: Supabase.instance.client.auth.currentUser!.id,
        justification: justification,
        aiSuggestion: aiSuggestion,
        finalDecision: finalDecision,
        createdAt: DateTime.now(),
      );

      await _repository.saveOverride(override);
      loadPendingReviews(); // Refresh
    } catch (e) {
      emit(AiReviewError(e.toString()));
    }
  }
}
